
Regz M. Pontanilla@LAPTOP-V0IU9RHQ MINGW64 ~
$ cd dev

Regz M. Pontanilla@LAPTOP-V0IU9RHQ MINGW64 ~/dev
$ cd ecommerce/

Regz M. Pontanilla@LAPTOP-V0IU9RHQ MINGW64 ~/dev/ecommerce
$ source virtual/Scripts/activate
(virtual)
Regz M. Pontanilla@LAPTOP-V0IU9RHQ MINGW64 ~/dev/ecommerce
$ cd virtual
(virtual)
Regz M. Pontanilla@LAPTOP-V0IU9RHQ MINGW64 ~/dev/ecommerce/virtual
$ cd ecommerce/
(virtual)
Regz M. Pontanilla@LAPTOP-V0IU9RHQ MINGW64 ~/dev/ecommerce/virtual/ecommerce
$ python manage.py runserver
Watching for file changes with StatReloader
[08/Aug/2020 12:57:20] "GET / HTTP/1.1" 200 5891
Not Found: /favicon.ico
[08/Aug/2020 12:57:21] "GET /favicon.ico HTTP/1.1" 404 3052
Not Found: /search
[08/Aug/2020 12:57:25] "GET /search HTTP/1.1" 404 3037
C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\ecommerce\ecommerce\urls.py ch                         anged, reloading.
Performing system checks...

System check identified no issues (0 silenced).
August 08, 2020 - 12:53:35
Django version 3.0.8, using settings 'ecommerce.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
Watching for file changes with StatReloader
[08/Aug/2020 12:57:43] "GET /search HTTP/1.1" 301 0
[08/Aug/2020 12:57:43] "GET /search/ HTTP/1.1" 200 8742
[08/Aug/2020 12:57:43] "GET /media/products/1171080419/1171080419.JPG HTTP/1.1"                          304 0
[08/Aug/2020 12:57:43] "GET /media/products/ecosolutions.JPG HTTP/1.1" 304 0
[08/Aug/2020 12:57:43] "GET /media/products/3148061780/3148061780.PNG HTTP/1.1"                          304 0
[08/Aug/2020 12:57:43] "GET /media/products/3102110313/3102110313.jpg HTTP/1.1"                          304 0
[08/Aug/2020 13:30:19] "GET /search/ HTTP/1.1" 200 8742
[08/Aug/2020 13:30:22] "GET /search/ HTTP/1.1" 200 8742
[08/Aug/2020 13:33:46] "GET /search/ HTTP/1.1" 200 8742
[08/Aug/2020 13:33:46] "GET /search/ HTTP/1.1" 200 8742
[08/Aug/2020 13:33:50] "GET /search/ HTTP/1.1" 200 8742
[08/Aug/2020 13:34:22] "GET /search/ HTTP/1.1" 200 8742
[08/Aug/2020 13:35:22] "GET /products/ HTTP/1.1" 200 8748
Not Found: /adin
[08/Aug/2020 13:35:29] "GET /adin HTTP/1.1" 404 3138
[08/Aug/2020 13:35:34] "GET /admin/ HTTP/1.1" 200 6701
[08/Aug/2020 13:35:34] "GET /static/admin/css/base.css HTTP/1.1" 200 16378
[08/Aug/2020 13:35:34] "GET /static/admin/css/dashboard.css HTTP/1.1" 200 412
[08/Aug/2020 13:35:34] "GET /static/admin/css/responsive.css HTTP/1.1" 200 18052
[08/Aug/2020 13:35:34] "GET /static/admin/css/fonts.css HTTP/1.1" 200 423
[08/Aug/2020 13:35:34] "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
[08/Aug/2020 13:35:34] "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200                          380
[08/Aug/2020 13:35:34] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP                         /1.1" 200 85876
[08/Aug/2020 13:35:34] "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1                         .1" 200 85692
[08/Aug/2020 13:35:34] "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.                         1" 200 86184
[08/Aug/2020 13:35:36] "GET /admin/products/product/ HTTP/1.1" 200 5843
[08/Aug/2020 13:35:36] "GET /static/admin/js/jquery.init.js HTTP/1.1" 200 363
[08/Aug/2020 13:35:36] "GET /admin/jsi18n/ HTTP/1.1" 200 3223
[08/Aug/2020 13:35:36] "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/                         1.1" 200 6918
[08/Aug/2020 13:35:36] "GET /static/admin/js/core.js HTTP/1.1" 200 5723
[08/Aug/2020 13:35:36] "GET /static/admin/js/actions.js HTTP/1.1" 200 6766
[08/Aug/2020 13:35:36] "GET /static/admin/js/urlify.js HTTP/1.1" 200 8941
[08/Aug/2020 13:35:36] "GET /static/admin/css/changelists.css HTTP/1.1" 200 6190
[08/Aug/2020 13:35:36] "GET /static/admin/js/prepopulate.js HTTP/1.1" 200 1530
[08/Aug/2020 13:35:36] "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1"                          200 128820
[08/Aug/2020 13:35:36] "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 2                         00 287630
[08/Aug/2020 13:35:36] "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 331
[08/Aug/2020 13:35:39] "GET /admin/products/product/add/ HTTP/1.1" 200 6695
[08/Aug/2020 13:35:39] "GET /static/admin/js/prepopulate_init.js HTTP/1.1" 200 4                         95
[08/Aug/2020 13:35:39] "GET /admin/jsi18n/ HTTP/1.1" 200 3223
[08/Aug/2020 13:35:39] "GET /static/admin/js/change_form.js HTTP/1.1" 200 712
[08/Aug/2020 13:35:39] "GET /static/admin/css/forms.css HTTP/1.1" 200 8518
[08/Aug/2020 13:35:39] "GET /static/admin/css/widgets.css HTTP/1.1" 200 10322
C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\ecommerce\search\urls.py chang                         ed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
August 08, 2020 - 12:57:40
Django version 3.0.8, using settings 'ecommerce.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
Watching for file changes with StatReloader

(virtual)
Regz M. Pontanilla@LAPTOP-V0IU9RHQ MINGW64 ~/dev/ecommerce/virtual/ecommerce
$ python manage.py runserver
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "C:\Users\Regz M. Pontanilla\AppData\Local\Programs\Python\Python36\lib\t                         hreading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Users\Regz M. Pontanilla\AppData\Local\Programs\Python\Python36\lib\t                         hreading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\djan                         go\utils\autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\djan                         go\core\management\commands\runserver.py", line 117, in inner_run
    self.check(display_num_errors=True)
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\djan                         go\core\management\base.py", line 395, in check
    include_deployment_checks=include_deployment_checks,
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\djan                         go\core\management\base.py", line 382, in _run_checks
    return checks.run_checks(**kwargs)
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\djan                         go\core\checks\registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\djan                         go\core\checks\urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\djan                         go\core\checks\urls.py", line 23, in check_resolver
    return check_method()
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\djan                         go\urls\resolvers.py", line 407, in check
    for pattern in self.url_patterns:
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\djan                         go\utils\functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\djan                         go\urls\resolvers.py", line 588, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\djan                         go\utils\functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\djan                         go\urls\resolvers.py", line 581, in urlconf_module
    return import_module(self.urlconf_name)
  File "C:\Users\Regz M. Pontanilla\AppData\Local\Programs\Python\Python36\lib\i                         mportlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Regz M. Pontanilla\dev\ecommerce\virtual\ecommerce\ecommerce\ur                         ls.py", line 47, in <module>
    path('search/', include(("search.urls", 'search'), namespace='search')),
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\djan                         go\urls\conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "C:\Users\Regz M. Pontanilla\AppData\Local\Programs\Python\Python36\lib\i                         mportlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Regz M. Pontanilla\dev\ecommerce\virtual\ecommerce\search\urls.                         py", line 8, in <module>
    path('',ProductListView.as_view(), name = 'list'),
NameError: name 'ProductListView' is not defined

C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\ecommerce\search\views.py chan                         ged, reloading.
Performing system checks...

Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "C:\Users\Regz M. Pontanilla\AppData\Local\Programs\Python\Python36\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Users\Regz M. Pontanilla\AppData\Local\Programs\Python\Python36\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\django\utils\autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\django\core\management\commands\runserver.py", line 117, in inner_run
    self.check(display_num_errors=True)
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\django\core\management\base.py", line 395, in check
    include_deployment_checks=include_deployment_checks,
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\django\core\management\base.py", line 382, in _run_checks
    return checks.run_checks(**kwargs)
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\django\core\checks\registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\django\core\checks\urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\django\core\checks\urls.py", line 23, in check_resolver
    return check_method()
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\django\urls\resolvers.py", line 407, in check
    for pattern in self.url_patterns:
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\django\utils\functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\django\urls\resolvers.py", line 588, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\django\utils\functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\django\urls\resolvers.py", line 581, in urlconf_module
    return import_module(self.urlconf_name)
  File "C:\Users\Regz M. Pontanilla\AppData\Local\Programs\Python\Python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Regz M. Pontanilla\dev\ecommerce\virtual\ecommerce\ecommerce\urls.py", line 47, in <module>
    path('search/', include(("search.urls", 'search'), namespace='search')),
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\django\urls\conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "C:\Users\Regz M. Pontanilla\AppData\Local\Programs\Python\Python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Regz M. Pontanilla\dev\ecommerce\virtual\ecommerce\search\urls.py", line 8, in <module>
    path('',ProductListView.as_view(), name = 'list'),
NameError: name 'ProductListView' is not defined

C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\ecommerce\search\urls.py changed, reloading.
Performing system checks...

Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "C:\Users\Regz M. Pontanilla\AppData\Local\Programs\Python\Python36\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Users\Regz M. Pontanilla\AppData\Local\Programs\Python\Python36\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\django\utils\autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\django\core\management\commands\runserver.py", line 117, in inner_run
    self.check(display_num_errors=True)
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\django\core\management\base.py", line 395, in check
    include_deployment_checks=include_deployment_checks,
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\django\core\management\base.py", line 382, in _run_checks
    return checks.run_checks(**kwargs)
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\django\core\checks\registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\django\core\checks\urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\django\core\checks\urls.py", line 23, in check_resolver
    return check_method()
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\django\urls\resolvers.py", line 407, in check
    for pattern in self.url_patterns:
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\django\utils\functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\django\urls\resolvers.py", line 588, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\django\utils\functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\django\urls\resolvers.py", line 581, in urlconf_module
    return import_module(self.urlconf_name)
  File "C:\Users\Regz M. Pontanilla\AppData\Local\Programs\Python\Python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Regz M. Pontanilla\dev\ecommerce\virtual\ecommerce\ecommerce\urls.py", line 47, in <module>
    path('search/', include(("search.urls", 'search'), namespace='search')),
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\django\urls\conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "C:\Users\Regz M. Pontanilla\AppData\Local\Programs\Python\Python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Regz M. Pontanilla\dev\ecommerce\virtual\ecommerce\search\urls.py", line 8, in <module>
    path('',ProductListView.as_view(), name = 'list'),
NameError: name 'ProductListView' is not defined

C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\ecommerce\search\urls.py changed, reloading.
Performing system checks...

Watching for file changes with StatReloader
[08/Aug/2020 13:42:08] "GET /search/ HTTP/1.1" 200 6453
[08/Aug/2020 13:52:08] "GET /search/?q=Pants HTTP/1.1" 200 6453
[08/Aug/2020 13:52:13] "GET /search/?q=ball HTTP/1.1" 200 6453
C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\ecommerce\search\views.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
August 08, 2020 - 13:42:07
Django version 3.0.8, using settings 'ecommerce.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
Watching for file changes with StatReloader
[08/Aug/2020 13:52:38] "GET /search/?q=ball HTTP/1.1" 200 6106
C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\ecommerce\search\views.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
August 08, 2020 - 13:52:37
Django version 3.0.8, using settings 'ecommerce.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
Watching for file changes with StatReloader
C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\ecommerce\search\views.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
August 08, 2020 - 13:52:58
Django version 3.0.8, using settings 'ecommerce.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
Watching for file changes with StatReloader
[08/Aug/2020 13:54:07] "GET /search/?q=ball HTTP/1.1" 200 6106
[08/Aug/2020 13:54:10] "GET /search/?q=ball HTTP/1.1" 200 6106
C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\ecommerce\search\views.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
August 08, 2020 - 13:54:03
Django version 3.0.8, using settings 'ecommerce.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
<QueryDict: {'q': ['ball']}>
<QueryDict: {'q': ['ball']}>
Watching for file changes with StatReloader
C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\ecommerce\search\views.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
August 08, 2020 - 13:54:16
Django version 3.0.8, using settings 'ecommerce.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
Watching for file changes with StatReloader
[08/Aug/2020 14:14:48] "GET /search/?q=ball HTTP/1.1" 200 6106
[08/Aug/2020 14:14:54] "GET /search/?q=mab HTTP/1.1" 200 6106
[08/Aug/2020 14:14:56] "GET /search/?q=mab HTTP/1.1" 200 6106
C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\ecommerce\search\views.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
August 08, 2020 - 14:14:43
Django version 3.0.8, using settings 'ecommerce.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
<QueryDict: {'q': ['ball']}>
ball
<QueryDict: {'q': ['mab']}>
mab
<QueryDict: {'q': ['mab']}>
mab
Watching for file changes with StatReloader
[08/Aug/2020 14:15:04] "GET /search/?q= HTTP/1.1" 200 6106
[08/Aug/2020 14:15:09] "GET /search/ HTTP/1.1" 200 5490
[08/Aug/2020 14:15:13] "GET /search/ HTTP/1.1" 200 5490
[08/Aug/2020 14:15:13] "GET /search/ HTTP/1.1" 200 5490
C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\ecommerce\search\views.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
August 08, 2020 - 14:15:02
Django version 3.0.8, using settings 'ecommerce.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
<QueryDict: {'q': ['']}>

<QueryDict: {}>
None
<QueryDict: {}>
None
<QueryDict: {}>
None
Watching for file changes with StatReloader
C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\ecommerce\search\views.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
August 08, 2020 - 14:19:35
Django version 3.0.8, using settings 'ecommerce.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
Watching for file changes with StatReloader
[08/Aug/2020 14:19:45] "GET /search/ HTTP/1.1" 200 6106
C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\ecommerce\search\views.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
August 08, 2020 - 14:19:45
Django version 3.0.8, using settings 'ecommerce.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
ball
Watching for file changes with StatReloader
[08/Aug/2020 14:19:56] "GET /search/ HTTP/1.1" 200 6106
[08/Aug/2020 14:20:01] "GET /search/ HTTP/1.1" 200 6106
C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\ecommerce\search\views.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
August 08, 2020 - 14:19:55
Django version 3.0.8, using settings 'ecommerce.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
pants
pants
Watching for file changes with StatReloader
[08/Aug/2020 14:20:06] "GET /search/ HTTP/1.1" 200 6106

(virtual)
Regz M. Pontanilla@LAPTOP-V0IU9RHQ MINGW64 ~/dev/ecommerce/virtual/ecommerce
$ python manage.py runserver
Watching for file changes with StatReloader
[08/Aug/2020 14:20:17] "GET /search/ HTTP/1.1" 200 6106
[08/Aug/2020 14:20:21] "GET /search/ HTTP/1.1" 200 6106
[08/Aug/2020 14:20:22] "GET /search/ HTTP/1.1" 200 6106
[08/Aug/2020 14:20:22] "GET /search/ HTTP/1.1" 200 6106
C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\ecommerce\search\views.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
August 08, 2020 - 14:20:16
Django version 3.0.8, using settings 'ecommerce.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
pants
pants
pants
pants
Watching for file changes with StatReloader
[08/Aug/2020 14:20:33] "GET /search/ HTTP/1.1" 200 6106
[08/Aug/2020 14:20:37] "GET /search/ HTTP/1.1" 200 6106
C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\ecommerce\search\views.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
August 08, 2020 - 14:20:27
Django version 3.0.8, using settings 'ecommerce.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
pants
pants
Watching for file changes with StatReloader
[08/Aug/2020 14:21:06] "GET /search/ HTTP/1.1" 200 6106
C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\ecommerce\search\views.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
August 08, 2020 - 14:21:02
Django version 3.0.8, using settings 'ecommerce.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
Pants
Watching for file changes with StatReloader
C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\ecommerce\search\views.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
August 08, 2020 - 14:21:14
Django version 3.0.8, using settings 'ecommerce.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
Watching for file changes with StatReloader
C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\ecommerce\search\views.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
August 08, 2020 - 14:21:17
Django version 3.0.8, using settings 'ecommerce.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
Watching for file changes with StatReloader
[08/Aug/2020 14:21:21] "GET /search/ HTTP/1.1" 200 5490
C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\ecommerce\search\views.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
August 08, 2020 - 14:21:21
Django version 3.0.8, using settings 'ecommerce.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
None
Watching for file changes with StatReloader
C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\ecommerce\search\views.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
August 08, 2020 - 14:21:38
Django version 3.0.8, using settings 'ecommerce.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
Watching for file changes with StatReloader
[08/Aug/2020 14:21:49] "GET /search/ HTTP/1.1" 200 6453
C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\ecommerce\search\views.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
August 08, 2020 - 14:21:48
Django version 3.0.8, using settings 'ecommerce.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
pants
Watching for file changes with StatReloader
Internal Server Error: /search/
Traceback (most recent call last):
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\django\views\generic\base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\django\views\generic\list.py", line 142, in get
    self.object_list = self.get_queryset()
  File "C:\Users\Regz M. Pontanilla\dev\ecommerce\virtual\ecommerce\search\views.py", line 14, in get_queryset
    return Product.objects.featured()
AttributeError: 'ProductManager' object has no attribute 'featured'
[08/Aug/2020 14:24:23] "GET /search/ HTTP/1.1" 500 90928
C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\ecommerce\search\views.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
August 08, 2020 - 14:24:22
Django version 3.0.8, using settings 'ecommerce.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
None
Watching for file changes with StatReloader
[08/Aug/2020 14:26:15] "GET /search/ HTTP/1.1" 200 6983
[08/Aug/2020 14:26:25] "GET /products/computer/ HTTP/1.1" 200 5643
[08/Aug/2020 14:26:34] "GET /products/batanes/ HTTP/1.1" 200 6179
[08/Aug/2020 14:37:42] "GET /products/batanes/ HTTP/1.1" 200 6179
[08/Aug/2020 14:37:50] "GET /search/ HTTP/1.1" 200 6983
C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\ecommerce\search\views.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
August 08, 2020 - 14:26:14
Django version 3.0.8, using settings 'ecommerce.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
None
None
Watching for file changes with StatReloader
Not Found: /search/q=pants
[08/Aug/2020 14:38:41] "GET /search/q=pants HTTP/1.1" 404 3230
[08/Aug/2020 14:38:50] "GET /search/?q=pants HTTP/1.1" 200 0
[08/Aug/2020 14:39:16] "GET /search/?q=ball HTTP/1.1" 200 0
[08/Aug/2020 14:39:27] "GET /search/?q=mab HTTP/1.1" 200 0
[08/Aug/2020 14:39:30] "GET /search/?q=mab HTTP/1.1" 200 0
C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\ecommerce\search\views.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
August 08, 2020 - 14:38:24
Django version 3.0.8, using settings 'ecommerce.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
pants
ball
mab
mab
Watching for file changes with StatReloader
[08/Aug/2020 14:39:43] "GET /search/?q=mab HTTP/1.1" 200 5529
[08/Aug/2020 14:39:49] "GET /search/?q=pants HTTP/1.1" 200 6486
[08/Aug/2020 14:41:35] "GET /search/?q=pants HTTP/1.1" 200 6527
Internal Server Error: /search/
Traceback (most recent call last):
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\django\template\base.py", line 469, in parse
    compile_func = self.tags[command]
KeyError: 'endblock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\django\core\handlers\base.py", line 145, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\django\core\handlers\base.py", line 143, in _get_response
    response = response.render()
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\django\template\response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\django\template\response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\django\template\loaders\base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\django\template\base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\django\template\base.py", line 194, in compile_nodelist
    return parser.parse()
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\django\template\base.py", line 477, in parse
    raise self.error(token, e)
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\django\template\base.py", line 475, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\django\template\loader_tags.py", line 266, in do_extends
    nodelist = parser.parse()
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\django\template\base.py", line 477, in parse
    raise self.error(token, e)
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\django\template\base.py", line 475, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\django\template\loader_tags.py", line 209, in do_block
    nodelist = parser.parse(('endblock',))
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\django\template\base.py", line 477, in parse
    raise self.error(token, e)
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\django\template\base.py", line 475, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\django\template\defaulttags.py", line 952, in do_if
    nodelist = parser.parse(('elif', 'else', 'endif'))
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\django\template\base.py", line 471, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\django\template\base.py", line 527, in invalid_block_tag
    get_text_list(["'%s'" % p for p in parse_until], 'or'),
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 26: 'endblock', expected 'elif', 'else' or 'endif'. Did you forget to register or load this tag?
[08/Aug/2020 14:47:50] "GET /search/?q=pants HTTP/1.1" 500 178871
[08/Aug/2020 14:48:12] "GET /search/?q=pants HTTP/1.1" 200 6543
[08/Aug/2020 14:48:19] "GET /search/ HTTP/1.1" 200 6986
[08/Aug/2020 14:55:29] "GET /search/ HTTP/1.1" 200 6986
[08/Aug/2020 14:55:37] "GET /search/ HTTP/1.1" 200 7109
[08/Aug/2020 14:56:13] "GET /search/ HTTP/1.1" 200 7109
[08/Aug/2020 15:03:30] "GET /search/ HTTP/1.1" 200 7128
[08/Aug/2020 15:04:11] "GET /search/ HTTP/1.1" 200 7128
[08/Aug/2020 15:04:29] "GET /search/ HTTP/1.1" 200 7133
[08/Aug/2020 15:11:24] "GET /search/ HTTP/1.1" 200 7135
[08/Aug/2020 15:11:57] "GET /search/ HTTP/1.1" 200 7133
[08/Aug/2020 15:12:41] "GET /search/ HTTP/1.1" 200 7124
[08/Aug/2020 15:13:21] "GET /search/ HTTP/1.1" 200 7116
[08/Aug/2020 15:25:00] "GET /search/ HTTP/1.1" 200 7144
[08/Aug/2020 15:25:34] "GET /search/ HTTP/1.1" 200 7149
[08/Aug/2020 15:26:55] "GET /search/ HTTP/1.1" 200 7197
[08/Aug/2020 15:31:27] "GET /search/?q=ball HTTP/1.1" 200 6328
C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\ecommerce\search\views.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
August 08, 2020 - 14:39:35
Django version 3.0.8, using settings 'ecommerce.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
mab
pants
pants
pants
pants
None
None
None
None
None
None
None
None
None
None
None
None
None
None
ball
Watching for file changes with StatReloader
[08/Aug/2020 15:33:47] "GET /search/?q=ball HTTP/1.1" 200 6229
[08/Aug/2020 15:33:53] "GET /search/?q=ball HTTP/1.1" 200 6229
C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\ecommerce\search\views.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
August 08, 2020 - 15:31:42
Django version 3.0.8, using settings 'ecommerce.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
ball
ball
Watching for file changes with StatReloader
[08/Aug/2020 16:00:32] "GET /search/?q=ball HTTP/1.1" 200 6229
[08/Aug/2020 16:00:35] "GET /search/?q=ball HTTP/1.1" 200 6229
C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\ecommerce\search\views.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
August 08, 2020 - 16:00:30
Django version 3.0.8, using settings 'ecommerce.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
ball
ball
Watching for file changes with StatReloader
[08/Aug/2020 16:00:46] "GET /search/?q=ball HTTP/1.1" 200 6229
[08/Aug/2020 16:14:59] "GET /search/?q=ball HTTP/1.1" 200 6478
[08/Aug/2020 16:15:45] "GET /search/?q=ball HTTP/1.1" 200 6477
[08/Aug/2020 16:15:47] "GET /search/? HTTP/1.1" 200 7445
[08/Aug/2020 16:17:16] "GET /search/? HTTP/1.1" 200 7445
[08/Aug/2020 16:17:22] "GET /search/? HTTP/1.1" 200 7610
[08/Aug/2020 16:26:15] "GET /search/? HTTP/1.1" 200 7594
[08/Aug/2020 16:38:19] "GET /search/? HTTP/1.1" 200 7734
[08/Aug/2020 16:39:11] "GET /search/? HTTP/1.1" 200 7730
[08/Aug/2020 16:39:12] "GET /search/? HTTP/1.1" 200 7730
[08/Aug/2020 17:01:36] "GET /search/? HTTP/1.1" 200 7730
[08/Aug/2020 17:01:50] "GET /search/? HTTP/1.1" 200 7730
C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\ecommerce\search\urls.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
August 08, 2020 - 16:00:39
Django version 3.0.8, using settings 'ecommerce.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
ball
ball
ball
None
None
None
None
None
None
None
None
None
Watching for file changes with StatReloader
[08/Aug/2020 17:06:14] "GET /search/? HTTP/1.1" 200 7810
[08/Aug/2020 17:06:16] "GET /search/?q= HTTP/1.1" 200 9557
[08/Aug/2020 17:06:30] "GET /search/?q=pants HTTP/1.1" 200 6921
[08/Aug/2020 17:06:33] "GET /products/pants/ HTTP/1.1" 200 6081
[08/Aug/2020 17:07:26] "GET /products/pants/ HTTP/1.1" 200 6090
[08/Aug/2020 17:07:31] "GET /search/?q=pants HTTP/1.1" 200 6935
[08/Aug/2020 17:08:04] "GET /search/?q=marielle HTTP/1.1" 200 5986
C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\ecommerce\search\views.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
August 08, 2020 - 17:04:19
Django version 3.0.8, using settings 'ecommerce.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
None

pants
pants
marielle
Watching for file changes with StatReloader
[08/Aug/2020 17:45:50] "GET /search/?q=batanes HTTP/1.1" 200 6592
[08/Aug/2020 17:45:57] "GET /products/ HTTP/1.1" 200 9146
[08/Aug/2020 17:46:01] "GET /products/pants-9ox1/ HTTP/1.1" 200 6015
[08/Aug/2020 17:46:12] "GET /search/?q=pats HTTP/1.1" 200 5978
[08/Aug/2020 17:46:24] "GET /admin HTTP/1.1" 301 0
[08/Aug/2020 17:46:24] "GET /admin/ HTTP/1.1" 200 6701
[08/Aug/2020 17:46:41] "GET /admin/products/product/add/ HTTP/1.1" 200 6695
[08/Aug/2020 17:46:42] "GET /admin/jsi18n/ HTTP/1.1" 200 3223
[08/Aug/2020 17:47:29] "POST /admin/products/product/add/ HTTP/1.1" 302 0
[08/Aug/2020 17:47:29] "GET /admin/products/product/ HTTP/1.1" 200 6278
[08/Aug/2020 17:47:29] "GET /admin/jsi18n/ HTTP/1.1" 200 3223
[08/Aug/2020 17:47:29] "GET /static/admin/img/icon-yes.svg HTTP/1.1" 200 436
[08/Aug/2020 17:47:36] "GET /products/ HTTP/1.1" 200 9585
[08/Aug/2020 17:47:47] "GET /search/?q=headgear HTTP/1.1" 200 6421
[08/Aug/2020 17:47:52] "GET /admin/products/product/5/change/ HTTP/1.1" 200 7028
[08/Aug/2020 17:47:52] "GET /admin/jsi18n/ HTTP/1.1" 200 3223
[08/Aug/2020 17:47:52] "GET /static/admin/img/tooltag-arrowright.svg HTTP/1.1" 200 280
[08/Aug/2020 17:48:07] "POST /admin/products/product/5/change/ HTTP/1.1" 302 0
[08/Aug/2020 17:48:07] "GET /admin/products/product/ HTTP/1.1" 200 6282
[08/Aug/2020 17:48:07] "GET /admin/jsi18n/ HTTP/1.1" 200 3223
[08/Aug/2020 17:48:17] "GET /search/?q=headgear HTTP/1.1" 200 6881
C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\ecommerce\search\views.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
August 08, 2020 - 17:45:37
Django version 3.0.8, using settings 'ecommerce.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
Watching for file changes with StatReloader
C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\ecommerce\products\models.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
August 08, 2020 - 17:55:53
Django version 3.0.8, using settings 'ecommerce.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "C:\Users\Regz M. Pontanilla\AppData\Local\Programs\Python\Python36\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Users\Regz M. Pontanilla\AppData\Local\Programs\Python\Python36\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\django\utils\autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\django\core\management\commands\runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\django\utils\autoreload.py", line 76, in raise_last_exception
    raise _exception[1]
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\django\core\management\__init__.py", line 357, in execute
    autoreload.check_errors(django.setup)()
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\django\utils\autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\django\apps\registry.py", line 114, in populate
    app_config.import_models()
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\django\apps\config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "C:\Users\Regz M. Pontanilla\AppData\Local\Programs\Python\Python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Regz M. Pontanilla\dev\ecommerce\virtual\ecommerce\products\models.py", line 36
    return self..filter(lookups).distinct()
                ^
SyntaxError: invalid syntax

C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\ecommerce\products\models.py changed, reloading.
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "C:\Users\Regz M. Pontanilla\AppData\Local\Programs\Python\Python36\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Users\Regz M. Pontanilla\AppData\Local\Programs\Python\Python36\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\django\utils\autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\django\core\management\commands\runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\django\utils\autoreload.py", line 76, in raise_last_exception
    raise _exception[1]
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\django\core\management\__init__.py", line 357, in execute
    autoreload.check_errors(django.setup)()
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\django\utils\autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\django\apps\registry.py", line 114, in populate
    app_config.import_models()
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\django\apps\config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "C:\Users\Regz M. Pontanilla\AppData\Local\Programs\Python\Python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Regz M. Pontanilla\dev\ecommerce\virtual\ecommerce\products\models.py", line 36
    return self..filter(lookups).distinct()
                ^
SyntaxError: invalid syntax

C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\ecommerce\products\models.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /search/
Traceback (most recent call last):
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\django\views\generic\base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\django\views\generic\list.py", line 142, in get
    self.object_list = self.get_queryset()
  File "C:\Users\Regz M. Pontanilla\dev\ecommerce\virtual\ecommerce\search\views.py", line 22, in get_queryset
    lookups = Q(title__icontains=query) | Q(descriptions__icontains=query)
NameError: name 'Q' is not defined
[08/Aug/2020 17:56:25] "GET /search/?q=headgear HTTP/1.1" 500 91449
C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\ecommerce\search\views.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
August 08, 2020 - 17:56:24
Django version 3.0.8, using settings 'ecommerce.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
Watching for file changes with StatReloader
[08/Aug/2020 17:57:37] "GET /search/?q=headgear HTTP/1.1" 200 6881
[08/Aug/2020 17:57:42] "GET /search/?q=cap HTTP/1.1" 200 6871
[08/Aug/2020 17:57:44] "GET /search/?q=cap HTTP/1.1" 200 6871
[08/Aug/2020 17:57:49] "GET /search/?q=ball HTTP/1.1" 200 6590
[08/Aug/2020 17:57:52] "GET /search/?q=cap HTTP/1.1" 200 6871
[08/Aug/2020 17:57:55] "GET /search/?q=mab HTTP/1.1" 200 6512
C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\ecommerce\products\models.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
August 08, 2020 - 17:57:34
Django version 3.0.8, using settings 'ecommerce.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "C:\Users\Regz M. Pontanilla\AppData\Local\Programs\Python\Python36\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Users\Regz M. Pontanilla\AppData\Local\Programs\Python\Python36\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\django\utils\autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\django\core\management\commands\runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\django\utils\autoreload.py", line 76, in raise_last_exception
    raise _exception[1]
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\django\core\management\__init__.py", line 357, in execute
    autoreload.check_errors(django.setup)()
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\django\utils\autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\django\apps\registry.py", line 114, in populate
    app_config.import_models()
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\django\apps\config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "C:\Users\Regz M. Pontanilla\AppData\Local\Programs\Python\Python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Regz M. Pontanilla\dev\ecommerce\virtual\ecommerce\products\models.py", line 35
    lookups = Q(title__icontains=query) |
                                         ^
SyntaxError: invalid syntax

C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\ecommerce\products\models.py changed, reloading.
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "C:\Users\Regz M. Pontanilla\AppData\Local\Programs\Python\Python36\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Users\Regz M. Pontanilla\AppData\Local\Programs\Python\Python36\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\django\utils\autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\django\core\management\commands\runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\django\utils\autoreload.py", line 76, in raise_last_exception
    raise _exception[1]
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\django\core\management\__init__.py", line 357, in execute
    autoreload.check_errors(django.setup)()
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\django\utils\autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\django\apps\registry.py", line 114, in populate
    app_config.import_models()
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\django\apps\config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "C:\Users\Regz M. Pontanilla\AppData\Local\Programs\Python\Python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Regz M. Pontanilla\dev\ecommerce\virtual\ecommerce\products\models.py", line 35
    lookups = Q(title__icontains=query) |
                                         ^
SyntaxError: invalid syntax

C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\ecommerce\products\models.py changed, reloading.
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "C:\Users\Regz M. Pontanilla\AppData\Local\Programs\Python\Python36\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Users\Regz M. Pontanilla\AppData\Local\Programs\Python\Python36\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\django\utils\autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\django\core\management\commands\runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\django\utils\autoreload.py", line 76, in raise_last_exception
    raise _exception[1]
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\django\core\management\__init__.py", line 357, in execute
    autoreload.check_errors(django.setup)()
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\django\utils\autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\django\apps\registry.py", line 114, in populate
    app_config.import_models()
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\django\apps\config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "C:\Users\Regz M. Pontanilla\AppData\Local\Programs\Python\Python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Regz M. Pontanilla\dev\ecommerce\virtual\ecommerce\products\models.py", line 35
    lookups = Q(title__icontains=query) |
                                        ^
SyntaxError: invalid syntax

C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\ecommerce\products\models.py changed, reloading.
Watching for file changes with StatReloader
[08/Aug/2020 18:16:44] "GET /search/ HTTP/1.1" 200 7869
[08/Aug/2020 18:16:49] "GET /search/?q=cap HTTP/1.1" 200 6871
C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\ecommerce\products\models.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
August 08, 2020 - 18:16:42
Django version 3.0.8, using settings 'ecommerce.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
Watching for file changes with StatReloader
[08/Aug/2020 18:17:27] "GET /search/?q=cap HTTP/1.1" 200 6871
[08/Aug/2020 18:18:17] "GET /search/?q=9.99 HTTP/1.1" 200 9682
[08/Aug/2020 18:18:22] "GET /products/computer/ HTTP/1.1" 200 6039
[08/Aug/2020 18:18:53] "GET /search/?q=hat HTTP/1.1" 200 7502
[08/Aug/2020 18:21:17] "GET /search/?q=hat HTTP/1.1" 200 7502
[08/Aug/2020 18:21:42] "GET /search/?q=hat HTTP/1.1" 200 7508
[08/Aug/2020 18:21:55] "GET /search/?q=hat HTTP/1.1" 200 7508
[08/Aug/2020 18:21:55] "GET /search/?q=hat HTTP/1.1" 200 7508
C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\ecommerce\products\models.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
August 08, 2020 - 18:17:26
Django version 3.0.8, using settings 'ecommerce.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
Watching for file changes with StatReloader
C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\ecommerce\products\models.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
August 08, 2020 - 18:26:08
Django version 3.0.8, using settings 'ecommerce.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
Watching for file changes with StatReloader
[08/Aug/2020 18:26:48] "GET /search/?q=hat HTTP/1.1" 200 7508
[08/Aug/2020 18:26:49] "GET /search/?q=hat HTTP/1.1" 200 7508
C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\ecommerce\products\models.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
August 08, 2020 - 18:26:46
Django version 3.0.8, using settings 'ecommerce.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
Watching for file changes with StatReloader

(virtual)
Regz M. Pontanilla@LAPTOP-V0IU9RHQ MINGW64 ~/dev/ecommerce/virtual/ecommerce
$ python manage.py startapp tags
(virtual)
Regz M. Pontanilla@LAPTOP-V0IU9RHQ MINGW64 ~/dev/ecommerce/virtual/ecommerce
$ python manage.py runserver
Watching for file changes with StatReloader

(virtual)
Regz M. Pontanilla@LAPTOP-V0IU9RHQ MINGW64 ~/dev/ecommerce/virtual/ecommerce
$ python manage.py makemigrations
No changes detected
(virtual)
Regz M. Pontanilla@LAPTOP-V0IU9RHQ MINGW64 ~/dev/ecommerce/virtual/ecommerce
$ python manage.py makemigrations
No changes detected
(virtual)
Regz M. Pontanilla@LAPTOP-V0IU9RHQ MINGW64 ~/dev/ecommerce/virtual/ecommerce
$ python manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, products, sessions
Running migrations:
  No migrations to apply.
(virtual)
Regz M. Pontanilla@LAPTOP-V0IU9RHQ MINGW64 ~/dev/ecommerce/virtual/ecommerce
$ python manage.py runserver
Watching for file changes with StatReloader
[08/Aug/2020 18:45:18] "GET /admin/ HTTP/1.1" 200 6689
[08/Aug/2020 18:45:57] "GET /admin/ HTTP/1.1" 200 6689
[08/Aug/2020 18:45:58] "GET /admin/ HTTP/1.1" 200 6689

(virtual)
Regz M. Pontanilla@LAPTOP-V0IU9RHQ MINGW64 ~/dev/ecommerce/virtual/ecommerce
$ python manage.py makemigrations
No changes detected
(virtual)
Regz M. Pontanilla@LAPTOP-V0IU9RHQ MINGW64 ~/dev/ecommerce/virtual/ecommerce
$ python manage.py makemigrations
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\django\core\management\__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\django\core\management\__init__.py", line 377, in execute
    django.setup()
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\django\apps\registry.py", line 114, in populate
    app_config.import_models()
  File "C:\Users\Regz M. Pontanilla\Dev\ecommerce\virtual\lib\site-packages\django\apps\config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "C:\Users\Regz M. Pontanilla\AppData\Local\Programs\Python\Python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Regz M. Pontanilla\dev\ecommerce\virtual\ecommerce\tags\models.py", line 8, in <module>
    class Tag(models.Model):
  File "C:\Users\Regz M. Pontanilla\dev\ecommerce\virtual\ecommerce\tags\models.py", line 11, in Tag
    timestamp   = models.DateTimeFiel(auto_now_add=True)
AttributeError: module 'django.db.models' has no attribute 'DateTimeFiel'
(virtual)
Regz M. Pontanilla@LAPTOP-V0IU9RHQ MINGW64 ~/dev/ecommerce/virtual/ecommerce
$ python manage.py makemigrations
Migrations for 'tags':
  tags\migrations\0001_initial.py
    - Create model Tag
(virtual)
Regz M. Pontanilla@LAPTOP-V0IU9RHQ MINGW64 ~/dev/ecommerce/virtual/ecommerce
$ python manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, products, sessions, tags
Running migrations:
  Applying tags.0001_initial... OK
(virtual)
Regz M. Pontanilla@LAPTOP-V0IU9RHQ MINGW64 ~/dev/ecommerce/virtual/ecommerce
$ python manage.py runserver
Watching for file changes with StatReloader
[08/Aug/2020 18:48:32] "GET /admin/ HTTP/1.1" 200 7336
[08/Aug/2020 20:10:41] "GET /admin/tags/tag/ HTTP/1.1" 200 3138
[08/Aug/2020 20:10:41] "GET /admin/jsi18n/ HTTP/1.1" 200 3223
[08/Aug/2020 20:10:43] "GET /admin/tags/tag/add/ HTTP/1.1" 200 5982
[08/Aug/2020 20:10:43] "GET /admin/jsi18n/ HTTP/1.1" 200 3223
[08/Aug/2020 20:11:06] "POST /admin/tags/tag/add/ HTTP/1.1" 200 6166
[08/Aug/2020 20:11:06] "GET /admin/jsi18n/ HTTP/1.1" 200 3223
[08/Aug/2020 20:11:15] "POST /admin/tags/tag/add/ HTTP/1.1" 302 0
[08/Aug/2020 20:11:15] "GET /admin/tags/tag/ HTTP/1.1" 200 4462
[08/Aug/2020 20:11:15] "GET /admin/jsi18n/ HTTP/1.1" 200 3223
[08/Aug/2020 20:11:17] "GET /admin/tags/tag/add/ HTTP/1.1" 200 5982
[08/Aug/2020 20:11:17] "GET /admin/jsi18n/ HTTP/1.1" 200 3223
[08/Aug/2020 20:11:38] "POST /admin/tags/tag/add/ HTTP/1.1" 302 0
[08/Aug/2020 20:11:38] "GET /admin/tags/tag/ HTTP/1.1" 200 4676
[08/Aug/2020 20:11:38] "GET /admin/jsi18n/ HTTP/1.1" 200 3223
[08/Aug/2020 20:11:39] "GET /admin/tags/tag/add/ HTTP/1.1" 200 5982
[08/Aug/2020 20:11:39] "GET /admin/jsi18n/ HTTP/1.1" 200 3223
[08/Aug/2020 20:11:50] "POST /admin/tags/tag/add/ HTTP/1.1" 200 6167
[08/Aug/2020 20:11:50] "GET /admin/jsi18n/ HTTP/1.1" 200 3223
[08/Aug/2020 20:11:59] "POST /admin/tags/tag/add/ HTTP/1.1" 302 0
[08/Aug/2020 20:11:59] "GET /admin/tags/tag/ HTTP/1.1" 200 4891
[08/Aug/2020 20:11:59] "GET /admin/jsi18n/ HTTP/1.1" 200 3223
[08/Aug/2020 20:12:01] "GET /admin/tags/tag/add/ HTTP/1.1" 200 5982
[08/Aug/2020 20:12:01] "GET /admin/jsi18n/ HTTP/1.1" 200 3223
[08/Aug/2020 20:12:18] "GET /admin/products/ HTTP/1.1" 200 2464
[08/Aug/2020 20:13:37] "GET /admin/products/product/add/ HTTP/1.1" 200 6695
[08/Aug/2020 20:13:37] "GET /admin/jsi18n/ HTTP/1.1" 200 3223
[08/Aug/2020 20:26:50] "POST /admin/products/product/add/ HTTP/1.1" 302 0
[08/Aug/2020 20:26:50] "GET /admin/products/product/ HTTP/1.1" 200 6540
[08/Aug/2020 20:26:50] "GET /admin/jsi18n/ HTTP/1.1" 200 3223
[08/Aug/2020 20:26:58] "GET /admin/tags/tag/add/ HTTP/1.1" 200 6020
[08/Aug/2020 20:26:58] "GET /admin/jsi18n/ HTTP/1.1" 200 3223
[08/Aug/2020 20:27:16] "POST /admin/tags/tag/add/ HTTP/1.1" 302 0
[08/Aug/2020 20:27:16] "GET /admin/tags/tag/ HTTP/1.1" 200 5105
[08/Aug/2020 20:27:16] "GET /admin/jsi18n/ HTTP/1.1" 200 3223
[08/Aug/2020 20:29:20] "GET /search/?q=hat HTTP/1.1" 200 7508
[08/Aug/2020 20:29:20] "GET /media/products/3102110313/3102110313.jpg HTTP/1.1" 304 0
[08/Aug/2020 20:29:27] "GET /search/?q=hat HTTP/1.1" 200 7508
[08/Aug/2020 20:29:31] "GET /products/ HTTP/1.1" 200 10225
[08/Aug/2020 20:29:31] "GET /media/products/2474780095/2474780095.jpg HTTP/1.1" 200 167166

(virtual)
Regz M. Pontanilla@LAPTOP-V0IU9RHQ MINGW64 ~/dev/ecommerce/virtual/ecommerce
$ python manage.py shell
Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 17:00:18) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from tags.model import Tag
Traceback (most recent call last):
  File "<console>", line 1, in <module>
ModuleNotFoundError: No module named 'tags.model'
>>> from tags.models import Tag
  File "<console>", line 1
    from tags.models import Tag
    ^
SyntaxError: invalid syntax
>>> from tags.models import Tag
>>> Tag.objects.all()
<QuerySet [<Tag: Black>, <Tag: Pants>, <Tag: Outfit>, <Tag: Places>]>
>>> Tag.objects.last()
<Tag: Places>
>>> place = Tag.objects.last()
>>> place.title
'Places'
>>> place.slug
'place'
>>> place.active
True
>>> place.products
<django.db.models.fields.related_descriptors.create_forward_many_to_many_manager.<locals>.ManyRelatedManager object at 0x000001F1DDC8E6D8>
>>> place.products.all()
<ProductQuerySet [<Product: Batanes>, <Product: Surigao>]>
>>> place.products.all().last()
  File "<console>", line 1
    place.products.all().last()
    ^
Syntplace.products.all().last()
  Fiplace.products.all().last()
    ^
SyntaxError: invalid syntax
>>> place.products.all().last()
<Product: Surigao>
>>> exit()
(virtual)
Regz M. Pontanilla@LAPTOP-V0IU9RHQ MINGW64 ~/dev/ecommerce/virtual/ecommerce
$ ^Cthon manage.py runserver
(virtual)
Regz M. Pontanilla@LAPTOP-V0IU9RHQ MINGW64 ~/dev/ecommerce/virtual/ecommerce
$
